/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Phân hệ Tiếp Đón',
      items: [
        'phan-he-don-tiep/dang-nhap-chon-phong-tiep-don',
        'phan-he-don-tiep/chon-chuc-nang-tiep-don-2',
        'phan-he-don-tiep/chuc-nang-benh-nhan',
        'phan-he-don-tiep/chuc-nang-danh-sach-y-lenh',
        'phan-he-don-tiep/chuc-nang-doi-phong-kham',
        'phan-he-don-tiep/chuc-nang-ho-so-dieu-tri',
        'phan-he-don-tiep/chuc-nang-lich-su-dieu-tri',
        'phan-he-don-tiep/chuc-nang-sua-yeu-cau-kham',
      ],
    },
    {
      type: 'category',
      label: 'Phân hệ Phòng Khám',
      items: [
        'phan-he-phong-kham/dang-nhap-chon-phong-kham',
        'phan-he-phong-kham/giao-dien-phong-kham',
        'phan-he-phong-kham/chuc-nang-danh-sach-y-lenh',
        'phan-he-phong-kham/chuc-nang-ho-so-dieu-tri',
        'phan-he-phong-kham/chuc-nang-lich-su-dieu-tri',
        'phan-he-phong-kham/chuc-nang-man-hinh-cho',
        'phan-he-phong-kham/chuc-nang-sua-yeu-cau-kham',
        'phan-he-phong-kham/xu-ly-kham',
      ],
    },
    {
      type: 'category',
      label: 'Phân hệ Nội Trú',
      items: [
        'phan-he-noi-tru/dang-nhap-chon-buong-benh',
        'phan-he-noi-tru/giao-dien-buong-benh',
        'phan-he-noi-tru/tiep-nhan-benh-nhan-vao-khoa',
        'phan-he-noi-tru/tiep-nhan-benh-nhan-vao-khoa',
        'phan-he-noi-tru/xu-ly-dieu-tri',
        'phan-he-noi-tru/ket-thuc-dieu-tri',
        'phan-he-noi-tru/mot-so-loi-thuong-gap',
      ],
    },
/*    {
      type: 'category',
      label: 'Phân hệ Dược / Vật tư',
      items: [
        'phan-he-duoc-vat-tu/dang-nhap-chon-phong',
        'phan-he-duoc-vat-tu/tao-loai-thuoc-moi',
        'phan-he-duoc-vat-tu/tao-loai-vat-tu-moi',
        'phan-he-duoc-vat-tu/y-nghia-thong-tin-thuoc-vat-tu',
        'phan-he-duoc-vat-tu/danh-sach-loai-thuoc-vat-tu',
        'phan-he-duoc-vat-tu/them-moi-nha-cung-cap',
        'phan-he-duoc-vat-tu/quan-ly-thau',
        'phan-he-duoc-vat-tu/nhap-hang-tu-hoa-don',
        'phan-he-duoc-vat-tu/duyet-phieu-nhap-kho',
        'phan-he-duoc-vat-tu/danh-sach-lo-thuoc-vat-tu',
        'phan-he-duoc-vat-tu/kiem-tra-ton-kho',
        'phan-he-duoc-vat-tu/xem-the-kho-lich-su-xuat-nhap',
        'phan-he-duoc-vat-tu/xuat-don-thuoc-ngoai-tru',
        'phan-he-duoc-vat-tu/xuat-chuyen-kho',
        'phan-he-duoc-vat-tu/xuat-phieu-linh-noi-tru',
        'phan-he-duoc-vat-tu/duyet-phieu-tra-noi-tru',
        'phan-he-duoc-vat-tu/duyet-bu-co-so-tu-truc',
        'phan-he-duoc-vat-tu/tao-phieu-tra-nha-cung-cap',
        'phan-he-duoc-vat-tu/xuat-khac',
        'phan-he-duoc-vat-tu/bao-cao-duoc',
      ],
    },
    {
      type: 'category',
      label: 'Phân hệ Thu Ngân',
      items: [
        'phan-he-thu-ngan/dang-nhap-chon-phong-thu-ngan',
        'phan-he-thu-ngan/gioi-thieu-man-hinh-thu-ngan',
        'phan-he-thu-ngan/tao-so-bien-lai-hoa-don',
        'phan-he-thu-ngan/tim-kiem-benh-nhan',
        'phan-he-thu-ngan/y-nghia-mau-sac-vien-phi',
        'phan-he-thu-ngan/y-nghia-thong-tin-chi-tiet-vien-phi',
        'phan-he-thu-ngan/thao-tac-thanh-toan',
        'phan-he-thu-ngan/khoa-vien-phi',
        'phan-he-thu-ngan/duyet-khoa-bao-hiem',
        'phan-he-thu-ngan/lich-su-giao-dich',
        'phan-he-thu-ngan/xem-bang-ke-chi-phi',
        'phan-he-thu-ngan/huy-giao-dich',
        'phan-he-thu-ngan/mien-giam',
        'phan-he-thu-ngan/mo-khoa-ho-so',
        'phan-he-thu-ngan/bao-cao-vien-phi',
      ],
    },*/
  ],  
};

module.exports = sidebars;