/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Phân hệ Tiếp Đón',
      items: [
        'phan-he-don-tiep/dang-nhap-chon-phong-tiep-don',
        'phan-he-don-tiep/chon-chuc-nang-tiep-don-2',
        'phan-he-don-tiep/chuc-nang-benh-nhan',
        'phan-he-don-tiep/chuc-nang-danh-sach-y-lenh',
        'phan-he-don-tiep/chuc-nang-doi-phong-kham',
        'phan-he-don-tiep/chuc-nang-ho-so-dieu-tri',
        'phan-he-don-tiep/chuc-nang-lich-su-dieu-tri',
        'phan-he-don-tiep/chuc-nang-sua-yeu-cau-kham',
        'phan-he-don-tiep/chinh-sua-xoa-ho-so',
      ],
    },
    {
      type: 'category',
      label: 'Phân hệ Phòng Khám',
      items: [
        'phan-he-phong-kham/dang-nhap-chon-phong-kham',
        'phan-he-phong-kham/mau-sac-va-bieu-tuong',
        'phan-he-phong-kham/goi-benh-nhan-theo-stt',
        'phan-he-phong-kham/xu-ly-kham-va-chan-doan',
        'phan-he-phong-kham/chi-dinh-can-lam-sang',
        'phan-he-phong-kham/xem-ket-qua-can-lam-sang',
        'phan-he-phong-kham/ke-don-thuoc',
        'phan-he-phong-kham/in-lai-phieu-chi-dinh-don-thuoc',
        'phan-he-phong-kham/sua-xoa-chi-dinh-don-thuoc',
        'phan-he-phong-kham/xu-tri-sau-kham',
        'phan-he-phong-kham/hen-kham-va-giay-to-bhxh',
        'phan-he-phong-kham/tao-mau-xu-ly-kham',
        'phan-he-phong-kham/xem-lich-su-dieu-tri',
        'phan-he-phong-kham/mo-lai-ho-so',
      ],
    },
    {
      type: 'category',
      label: 'Phân hệ Nội Trú',
      items: [
        'phan-he-noi-tru/dang-nhap-dang-xuat-doi-mat-khau',
        'phan-he-noi-tru/chon-phong-lam-viec',
        'phan-he-noi-tru/tiep-nhan-benh-nhan-vao-khoa',
        'phan-he-noi-tru/man-hinh-buong-benh',
        'phan-he-noi-tru/ke-ngay-giuong',
        'phan-he-noi-tru/cap-nhat-doi-tuong-benh-nhan',
        'phan-he-noi-tru/chuyen-khoa',
        'phan-he-noi-tru/ket-thuc-dieu-tri',
        'phan-he-noi-tru/tao-to-dieu-tri',
        'phan-he-noi-tru/quan-ly-y-lenh',
        'phan-he-noi-tru/chi-dinh-dich-vu-ky-thuat',
        'phan-he-noi-tru/ke-don-thuoc',
        'phan-he-noi-tru/quan-ly-thuoc-tu-truc',
        'phan-he-noi-tru/tong-hop-phieu-linh',
        'phan-he-noi-tru/tao-phieu-tra',
        'phan-he-noi-tru/linh-hao-phi-khoa-phong',
        'phan-he-noi-tru/nhap-thong-tin-pttt',
        'phan-he-noi-tru/ke-vat-tu-hao-phi-pttt',
        'phan-he-noi-tru/bien-ban-hoi-chan',
        'phan-he-noi-tru/lam-benh-an',
        'phan-he-noi-tru/cong-khai-dich-vu',
        'phan-he-noi-tru/xem-va-in-bang-ke',
        'phan-he-noi-tru/cac-chuc-nang-khac',
      ],
    },
    {
      type: 'category',
      label: 'Phân hệ Dược / Vật tư',
      items: [
        'phan-he-duoc-vat-tu/dang-nhap-chon-phong',
        'phan-he-duoc-vat-tu/tao-loai-thuoc-moi',
        'phan-he-duoc-vat-tu/tao-loai-vat-tu-moi',
        'phan-he-duoc-vat-tu/y-nghia-thong-tin-thuoc-vat-tu',
        'phan-he-duoc-vat-tu/danh-sach-loai-thuoc-vat-tu',
        'phan-he-duoc-vat-tu/them-moi-nha-cung-cap',
        'phan-he-duoc-vat-tu/quan-ly-thau',
        'phan-he-duoc-vat-tu/nhap-hang-tu-hoa-don',
        'phan-he-duoc-vat-tu/duyet-phieu-nhap-kho',
        'phan-he-duoc-vat-tu/danh-sach-lo-thuoc-vat-tu',
        'phan-he-duoc-vat-tu/kiem-tra-ton-kho',
        'phan-he-duoc-vat-tu/xem-the-kho-lich-su-xuat-nhap',
        'phan-he-duoc-vat-tu/xuat-don-thuoc-ngoai-tru',
        'phan-he-duoc-vat-tu/xuat-chuyen-kho',
        'phan-he-duoc-vat-tu/xuat-phieu-linh-noi-tru',
        'phan-he-duoc-vat-tu/duyet-phieu-tra-noi-tru',
        'phan-he-duoc-vat-tu/duyet-bu-co-so-tu-truc',
        'phan-he-duoc-vat-tu/tao-phieu-tra-nha-cung-cap',
        'phan-he-duoc-vat-tu/xuat-khac',
        'phan-he-duoc-vat-tu/bao-cao-duoc',
      ],
    },
    {
      type: 'category',
      label: 'Phân hệ Thu Ngân',
      items: [
        'phan-he-thu-ngan/dang-nhap-chon-phong-thu-ngan',
        'phan-he-thu-ngan/gioi-thieu-man-hinh-thu-ngan',
        'phan-he-thu-ngan/tao-so-bien-lai-hoa-don',
        'phan-he-thu-ngan/tim-kiem-benh-nhan',
        'phan-he-thu-ngan/y-nghia-mau-sac-vien-phi',
        'phan-he-thu-ngan/y-nghia-thong-tin-chi-tiet-vien-phi',
        'phan-he-thu-ngan/thao-tac-thanh-toan',
        'phan-he-thu-ngan/khoa-vien-phi',
        'phan-he-thu-ngan/duyet-khoa-bao-hiem',
        'phan-he-thu-ngan/lich-su-giao-dich',
        'phan-he-thu-ngan/xem-bang-ke-chi-phi',
        'phan-he-thu-ngan/huy-giao-dich',
        'phan-he-thu-ngan/mien-giam',
        'phan-he-thu-ngan/mo-khoa-ho-so',
        'phan-he-thu-ngan/bao-cao-vien-phi',
      ],
    },
  ],
};

module.exports = sidebars;